server:
  port: 7005
  
spring:  data:    elasticsearch:
      cluster-name: docker-cluster      cluster-nodes: 192.168.99.100:9300         properties: {client.transport.sniff: false}
       