server:
  port: 7003
spring:  application:    name: spring-cloud-gateway
  zipkin:
    locator:
      discovery:
        enabled: true
    base-url: http://192.168.99.100:9411/
  sleuth:
    sampler:
      probability: 0.5
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/  instance:    instance-id: gateway.com
    prefer-ip-address: true
zuul:
  ignoredServices: '*'
  routes:
    user: 
     path: /myuser/**
     serviceId: spring-cloud-user
    order:
      path: /myorder/**
      serviceId: spring-cloud-order