server:
  port: 7002
spring:  application:    name: spring-cloud-user
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/
  instance:
    instance-id: spring-cloud-user